import { ModelSettings } from '../services/ModelSettingsService';
import { Platform } from 'react-native';
export const DEFAULT_SETTINGS: ModelSettings = {
  maxTokens: 4096,
  temperature: 0.7,
  topK: 40,
  topP: 0.9,
  minP: 0.05,
  stopWords: ['<|end|>', '<end_of_turn>', '<|im_end|>', '<|endoftext|>', '<end_of_utterance>', '<turn|>'],
  systemPrompt: '',
  jinja: true,
  grammar: '',
  nProbs: 0,
  penaltyLastN: 64,
  penaltyRepeat: 1.0,
  penaltyFreq: 0.0,
  penaltyPresent: 0.0,
  mirostat: 0,
  mirostatTau: 5.0,
  mirostatEta: 0.1,
  dryMultiplier: 0.0,
  dryBase: 1.75,
  dryAllowedLength: 2,
  dryPenaltyLastN: -1,
  drySequenceBreakers: ['\n', ':', '"', '*'],
  ignoreEos: false,
  logitBias: [],
  seed: -1,
  xtcProbability: 0.0,
  xtcThreshold: 0.1,
  typicalP: 1.0,
  enableThinking: true,
  includeThinkingTokens: false,
};
export const LLAMA_INIT_CONFIG = {
  use_mlock: false,
  use_mmap: Platform.OS === 'android' ? 'smart' : 'true',
  n_ctx: 4096,
  n_batch: 512,
  n_ubatch: 512,
  n_parallel: 1,
  n_threads: 4,
  cache_type_k: 'f16',
  cache_type_v: 'f16',
  n_gpu_layers: 99,
  flash_attn_type: Platform.OS === 'ios' ? 'auto' : 'off',
  kv_unified: true,
  no_extra_bufts: false,
  devices: undefined,
  embedding: true,
  ctx_shift: false,
};
export const TOKEN_PROCESSING_CONFIG = {
  maxWaitTime: 5000,
  checkInterval: 50,
};
export const TITLE_GENERATION_CONFIG = {
  maxTokens: 50,
  temperature: 0.3,
  topK: 30,
  topP: 0.8,
  minP: 0.05,
  maxTitleLength: 50,
};
