apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
  namespace "expo.modules.rootaccess"
  compileSdk 36

  defaultConfig {
    minSdk 28
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = "17"
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "androidx.core:core-ktx:1.15.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"
  implementation "com.github.topjohnwu.libsu:core:6.0.0"
}
